"""initial

Revision ID: 3a1268de07b0
Revises: 
Create Date: 2026-04-15 19:06:24.439290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a1268de07b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('issue', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('issue', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issue', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('issue', 'updated_at')
    op.drop_column('issue', 'created_at')
    # ### end Alembic commands ###
