"""add projects and model updates on issue

Revision ID: c7ffb7c89a04
Revises: 97c6fbd4d4cf
Create Date: 2026-04-27 16:20:24.849783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7ffb7c89a04'
down_revision: Union[str, Sequence[str], None] = '97c6fbd4d4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('issue', sa.Column('reporter_id', sa.Integer(), nullable=True))
    op.add_column('issue', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('issue', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issue', 'user', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'issue', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'issue', 'user', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.drop_column('issue', 'project_id')
    op.drop_column('issue', 'assignee_id')
    op.drop_column('issue', 'reporter_id')
    op.drop_table('project')
    # ### end Alembic commands ###
